package org.xottys.persistencestore;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bankAccountDaoConfig;

    private final BankAccountDao bankAccountDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bankAccountDaoConfig = daoConfigMap.get(BankAccountDao.class).clone();
        bankAccountDaoConfig.initIdentityScope(type);

        bankAccountDao = new BankAccountDao(bankAccountDaoConfig, this);

        registerDao(BankAccount.class, bankAccountDao);
    }
    
    public void clear() {
        bankAccountDaoConfig.clearIdentityScope();
    }

    public BankAccountDao getBankAccountDao() {
        return bankAccountDao;
    }

}
